TRACKS = [ 
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"1xyEZ7bacBb97ucPS7PXMM", :title=>"Xtal", :track_number=>1, :duration_ms=>294053, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"6MTR1iU2ndeDGqdswM4ucH", :title=>"Tha", :track_number=>2, :duration_ms=>547133, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"6IhRKyuNFDu4aR0YlT9Nlm", :title=>"Pulseid", :track_number=>3, :duration_ms=>228053, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"78RRs3YvNvgl9ribbpisrV", :title=>"Ageispolis", :track_number=>4, :duration_ms=>323186, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"770urYRt3t7vImMY8106hB", :title=>"I", :track_number=>5, :duration_ms=>77346, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"36hhQwHK0cIoXp41HInqFE", :title=>"Green Calx", :track_number=>6, :duration_ms=>365160, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"3qWYkPDHWPC9hXpKPnXVOA", :title=>"Heliosphan", :track_number=>7, :duration_ms=>293800, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"2RtoZ1emlJTQIHrnsSwF8z", :title=>"We Are the Music Makers", :track_number=>8, :duration_ms=>463520, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"67U73wCqfKtki44XIWfs2o", :title=>"Schottkey 7th Path", :track_number=>9, :duration_ms=>308720, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"05xRbyPYyXf23p8drZ3EmP", :title=>"Ptolemy", :track_number=>10, :duration_ms=>434306, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"1JjRSfDedeOuRy1azhMiZW", :title=>"Hedphelym", :track_number=>11, :duration_ms=>363920, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"3jIc6J1T6JQDS2382BZrOk", :title=>"Delphium", :track_number=>12, :duration_ms=>329266, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"1Xdzq7uZAv640cXUoeAFAZ", :track_id=>"6JnvRzy54RWBvzRFIQZjUV", :title=>"Actium", :track_number=>13, :duration_ms=>455000, :album_name=>"Selected Ambient Works 85-92", :artists=>"Aphex Twin"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"2BOUrjXoRIo2YHVAyZyXVX", :title=>"Colors", :track_number=>1, :duration_ms=>261741, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"3GevDZnRimIO7bX0ulCbVU", :title=>"Seventh Heaven", :track_number=>2, :duration_ms=>300590, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"7qJ0DVXgKBB2tJeQpe8pP6", :title=>"I'm So Free", :track_number=>3, :duration_ms=>247970, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"6ecAkpOqGXQOkISSy5WWfi", :title=>"Dear Life", :track_number=>4, :duration_ms=>224237, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"2LJhMEdHmHXtzR8oJaNy3m", :title=>"No Distraction", :track_number=>5, :duration_ms=>272423, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"7yVCPF2RjQaQkPV0SylA5p", :title=>"Dreams - Colors Mix", :track_number=>6, :duration_ms=>296996, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"1rEkUEBFYEtqDLYaTuElsx", :title=>"Wow", :track_number=>7, :duration_ms=>222335, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"28AgTOIZke8nitD0NNeb3G", :title=>"Up All Night", :track_number=>8, :duration_ms=>190447, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"7amNVB6DyXQVHyfwRlc1Q0", :title=>"Square One", :track_number=>9, :duration_ms=>175524, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"68VHAzUy9eyqfUl4mS4mft", :title=>"Fix Me", :track_number=>10, :duration_ms=>193393, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"6BOQkxcHspMoRWEwEexf4l", :track_id=>"14zhqtMI5xHrfCFCLhFcsn", :title=>"Dreams", :track_number=>11, :duration_ms=>314486, :album_name=>"Colors", :artists=>"Beck"},
  {:album_id=>"0IXETEEklsep4cCfp15gdF", :track_id=>"7GDgkMlXo3Fq6L2nJx3bW1", :title=>"Somatic Serenade", :track_number=>1, :duration_ms=>467832, :album_name=>"Cosmic Dubs", :artists=>"Bluetech"},
  {:album_id=>"0IXETEEklsep4cCfp15gdF", :track_id=>"4XKxSMJUr3VRoLOjy8xzJ8", :title=>"Cosmic Trigger", :track_number=>2, :duration_ms=>392530, :album_name=>"Cosmic Dubs", :artists=>"Bluetech"},
  {:album_id=>"0IXETEEklsep4cCfp15gdF", :track_id=>"63F4nMhIQf5J3eDuuj3tQX", :title=>"Wandering Spirals", :track_number=>3, :duration_ms=>411976, :album_name=>"Cosmic Dubs", :artists=>"Bluetech"},
  {:album_id=>"0IXETEEklsep4cCfp15gdF", :track_id=>"5OPvQXjEsjP7L2Os8RL2ad", :title=>"Dersu the Trapper", :track_number=>4, :duration_ms=>449942, :album_name=>"Cosmic Dubs", :artists=>"Bluetech"},
  {:album_id=>"0IXETEEklsep4cCfp15gdF", :track_id=>"0IjMF4fOFxDbL88mtatcYL", :title=>"Point Cloud", :track_number=>5, :duration_ms=>410680, :album_name=>"Cosmic Dubs", :artists=>"Bluetech"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"3jOx0hdiz9EOZFHUBYdj6L", :title=>"Build Voice", :track_number=>1, :duration_ms=>328000, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"31TNZRKdcAi8DBchNG8JGG", :title=>"Red F", :track_number=>2, :duration_ms=>278373, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"2kEUnoIRejGTX3y8oH3euY", :title=>"Paddling Ghost", :track_number=>3, :duration_ms=>245866, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"5UKKQVjIyCg6F57gulETXr", :title=>"Snookered", :track_number=>4, :duration_ms=>484373, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"082UBCOIFyswldW49b8dyA", :title=>"Of The Mountains", :track_number=>5, :duration_ms=>436026, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"6FtPpT5Qg8POcfVfGalTrL", :title=>"Surprise Stefani", :track_number=>6, :duration_ms=>466000, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"2IpVYZLoJi4yNw2T8ymMSH", :title=>"Wet Wings", :track_number=>7, :duration_ms=>173026, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"7tvHJ3UIPGFCsD8VAgLI6V", :title=>"Woof Woof", :track_number=>8, :duration_ms=>284000, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"36Kfpkogj914IRdx3wSV58", :title=>"Slow With Horns / Run For Your Life", :track_number=>9, :duration_ms=>395000, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"1daKvFDTYnzih7GncTDQvA", :title=>"Baltihorse", :track_number=>10, :duration_ms=>381826, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"6SsP7QnagGoYqMRsxryQu5", :track_id=>"0j2CfpbAkWsoKyGxhN0Fjd", :title=>"Get Older", :track_number=>11, :duration_ms=>390000, :album_name=>"Bromst", :artists=>"Dan Deacon"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"3Zp3USxEQ90N4od238p2b5", :title=>"Convinced Of The Hex", :track_number=>1, :duration_ms=>234813, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"4oX8GTGxB4oJeCJNdxwNvE", :title=>"The Sparrow Looks Up At The Machine", :track_number=>2, :duration_ms=>250786, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"0sinBjx4PRdzgRe9vVF8wK", :title=>"Evil", :track_number=>3, :duration_ms=>338400, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"6afd0Txh94Lu5GYvxRPQs1", :title=>"Aquarius Sabotage", :track_number=>4, :duration_ms=>130440, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"2FK4pP9NVxX9QqpROxH98I", :title=>"See The Leaves", :track_number=>5, :duration_ms=>264266, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"6Ukjzq4pqMWZNb8Rpxypz1", :title=>"If", :track_number=>6, :duration_ms=>124893, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"2Q8AQWyz5bdlTc9CSWmdaT", :title=>"Gemini Syringes", :track_number=>7, :duration_ms=>221320, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"1dxkK6cndXWxVCFJnYo36R", :title=>"Your Bats", :track_number=>8, :duration_ms=>154920, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"4V9JPQvJ85H5KtQrVsJ529", :title=>"Powerless", :track_number=>9, :duration_ms=>417453, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"4yuSA23gP1O7ceL5F1NJ0W", :title=>"The Ego's Last Stand", :track_number=>10, :duration_ms=>339986, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"2ClvpcPA3rHskVXNQlma46", :title=>"I Can Be A Frog", :track_number=>11, :duration_ms=>134373, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"79KF8UJvyYqiDQTdB5mI89", :title=>"Sagittarius Silver Announcement", :track_number=>12, :duration_ms=>178786, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"2HE1XGVYm6AVtLgO7RUpPH", :title=>"Worm Mountain", :track_number=>13, :duration_ms=>321706, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"2kHtUfzIgBvDK4ElaKeMtR", :title=>"Scorpio Sword", :track_number=>14, :duration_ms=>121733, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"47ZvGlJb5wjdqYlfBkBjZA", :title=>"The Impulse", :track_number=>15, :duration_ms=>246720, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"4yYKWN3FtoRxdlJBqIn8Rh", :title=>"Silver Trembling Hands", :track_number=>16, :duration_ms=>238973, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"1bLjnu67WJ2Rgrw9sMF7w1", :title=>"Virgo Self-Esteem Broadcast", :track_number=>17, :duration_ms=>224120, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"4Gucn0d30QiZSrXrcNVjhk", :track_id=>"0YpJE88fA2iBfez12b9b90", :title=>"Watching The Planets", :track_number=>18, :duration_ms=>316853, :album_name=>"Embryonic", :artists=>"The Flaming Lips"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"5wEGNeGw9QPdgU26BGkXIs", :title=>"Stay Humble", :track_number=>1, :duration_ms=>146170, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"5jod7vbt4HAXOgiqA2aqKL", :title=>"idght in Montreal", :track_number=>2, :duration_ms=>233526, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"01TeWe9FtQOOoO1xDid", :title=>"Groovin '", :track_number=>3, :duration_ms=>213559, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"7MOzUTGrhzDgjrwv77OAD8", :title=>"Future Lounge", :track_number=>4, :duration_ms=>211210, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"7FR4WW2R3Zk5th3JYP4sz8", :title=>"She Loved Me", :track_number=>5, :duration_ms=>204255, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"5ny80fmmybUDPLAp5HZ8QV", :title=>"Can It Be", :track_number=>6, :duration_ms=>151744, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"66uRh8bWIT9Siv4SZYGdEl", :title=>"My Lady", :track_number=>7, :duration_ms=>191418, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"1sfunK61b9awtDjo3J5AZT", :title=>"Cup of Ramen", :track_number=>8, :duration_ms=>163555, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"1ZjufjQtqfI1It02pwjtLA", :title=>"Slepplessness", :track_number=>9, :duration_ms=>148936, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"0MgmXt8RU3835yaXQRjIo0", :title=>"Cheer Up", :track_number=>10, :duration_ms=>236888, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"2HfqbuhZSX6vbuA5BNKRmI", :title=>"Helping Hand", :track_number=>11, :duration_ms=>164672, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"7HIQwXtGY23CCkxp5mHb5v", :track_id=>"6zTdmVcqFqMIMv58QpJkok", :title=>"Bushwick Boogie", :track_number=>12, :duration_ms=>226875, :album_name=>"Kahunastyle", :artists=>"Flamingosis"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"0IvQCuL8N4158edtz98LCL", :title=>"Wasted Acres", :track_number=>1, :duration_ms=>172160, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"0szSOfZVM3G5mWI1ogQjr7", :title=>"Mourning Sound", :track_number=>2, :duration_ms=>262106, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"3tcHkc9jBM18J3qvYaiSLN", :title=>"Four Cypresses", :track_number=>3, :duration_ms=>288053, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"7EMtXthSsYKASqvqqBrFX0", :title=>"Three Rings", :track_number=>4, :duration_ms=>288813, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"2ZRvcRcKdwQBjTAqj2XNJN", :title=>"Losing All Sense", :track_number=>5, :duration_ms=>305866, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"5V0XNa6xutqC0IRf8HEXb1", :title=>"Aquarian", :track_number=>6, :duration_ms=>257933, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"7pVw7bTWnOTLPv3DzZT44T", :title=>"Cut-Out", :track_number=>7, :duration_ms=>225733, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"1kNXIFMQdNBV0no16EC79p", :title=>"Glass Hillid", :track_number=>8, :duration_ms=>293733, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"0y5eXIOgRZreQOFDss6mzQ", :title=>"Neighbors", :track_number=>9, :duration_ms=>284400, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"0TmI6JF8ZTO7kWl3pG777B", :title=>"Systole", :track_number=>10, :duration_ms=>196133, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"3QOXA8bqsml8CslUdgHXrW", :track_id=>"0AhQsGobGb5WDQEc0ExKSR", :title=>"Sky Took Hold", :track_number=>11, :duration_ms=>332680, :album_name=>"Painted Ruins", :artists=>"Grizzly Bear"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"5J1HmHmp6zCsSfHGkaeF53", :title=>"We Disappear", :track_number=>1, :duration_ms=>290120, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"5aBdWL4ud0ovtDJIJGQLdc", :title=>"Open Eye Signal", :track_number=>2, :duration_ms=>468586, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"69Xd9INPcqQf6xD5pIp2cv", :title=>"Breathe This Air", :track_number=>3, :duration_ms=>329906, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"5XjMiEdwKwdhBp3IpbJJeE", :title=>"Colid", :track_number=>4, :duration_ms=>561693, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"6ONMIrYmLAF2523vlCQclj", :title=>"Abandon Window", :track_number=>5, :duration_ms=>297493, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"4FkbgMPwUcZ1Ysi8OOq9Z5", :title=>"Form By Firelight", :track_number=>6, :duration_ms=>345066, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"4WpqAzzZo04LS5jrze14rM", :title=>"Sun Harmonics", :track_number=>7, :duration_ms=>714093, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"7H7UxuxjGSJuV7LcCFUxTD", :track_id=>"2pQV1J8zokISM1Ew5uSGI1", :title=>"Immunity", :track_number=>8, :duration_ms=>596773, :album_name=>"Immunity", :artists=>"Jon Hopkins"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"0qpzxYvwXffvgeuPJge0mu", :title=>"Not Up To Me", :track_number=>1, :duration_ms=>136199, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"691J4wzB8KEHMONyoZhxw8", :title=>"Charlie's Party", :track_number=>2, :duration_ms=>134506, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"2uhJQWW2YzWGsPPafWcI14", :title=>"Darker Parts", :track_number=>3, :duration_ms=>320333, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"1j2Ls2cuXrIjGl6abH07Do", :title=>"Untitled III", :track_number=>4, :duration_ms=>185466, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"44HhCEPX9mrylVhiCSMRHU", :title=>"Shades", :track_number=>5, :duration_ms=>350986, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"2NKQR67sItxdLmZTywH0Az", :title=>"Don't Hold Me Now", :track_number=>6, :duration_ms=>173599, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"6v5H6C7qW4Oel58Pi8ahKn", :title=>"Dress Up", :track_number=>7, :duration_ms=>384720, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"10gFw6wg2FTDg4vSHW9kKM", :title=>"Dugout", :track_number=>8, :duration_ms=>286560, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"0h1XKzxZiJ9BdR4gqu8oQt", :title=>"36 Grams Of Sugar", :track_number=>9, :duration_ms=>114653, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"2myJL6uPFUqfjlGBlEKSuL", :title=>"Knots", :track_number=>10, :duration_ms=>208386, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"},
  {:album_id=>"6039zdfJvRU1oa8JRhGGmJ", :track_id=>"2ybc8FwdLOD6YsGGjwkVUz", :title=>"Guay Lo", :track_number=>11, :duration_ms=>674053, :album_name=>"magnetkingmagnetqueen", :artists=>"New Madrid"}
]
